
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app-container
          image: nginx:1.21.6
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          env:
            - name: APP_CONFIG_PATH
              value: "/etc/config/app-config.yaml"
          ports:
            - containerPort: 80
      volumes:
        - name: config-volume
          configMap:
            name: app-config
