---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: busybox
          command: ["sh", "-c", "wget -qO- \"$BACKEND_URL\" || exit 1; sleep 3600"]
          env:
            - name: BACKEND_UR
              value: "http://backend-service:8080"
          ports:
            - containerPort: 80
