
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-deployment
  labels:
    app: broken-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: broken-app
  template:
    metadata:
      labels:
        app: broken-app
    spec:
      containers:
        - name: broken-container
          image: nginx:1.21.6
          ports:
            - containerPort: 80
